version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: noteapi
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: note-v1
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:


# docker run --name noteapi -e 
# POSTGRES_PASSWORD=test -e 
# POSTGRES_USER=test -e 
# POSTGRES_DB=note-v1 -p 5432:5432 -d postgres